[manifest]
version = "0.0.0"
dump_lua = true
priority = 233

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end'''
match_indent = true
position = "after"
payload = '''
-- context.just_before
SMODS.calculate_context({full_hand = G.play.cards, scoring_hand = scoring_hand, scoring_name = text, poker_hands = poker_hands, just_before = true})
'''

## tree sapling and above

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
	elseif to_big(G.GAME.dollars) >= to_big(5) and not G.GAME.modifiers.no_interest then
        add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)})'''
match_indent = true
position = "at"
payload = '''
	elseif to_big(G.GAME.dollars) >= to_big(G.GAME.interest_factor or 5) and not G.GAME.modifiers.no_interest then
        add_round_eval_row({bonus = true, name='interest', pitch = pitch, dollars = G.get_interest_num(false).money})'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
                elseif config.name == 'interest' then
                    table.insert(left_text, {n=G.UIT.T, config={text = num_dollars, scale = 0.8*scale, colour = G.C.MONEY, shadow = true, juice = true}})
                    table.insert(left_text,{n=G.UIT.O, config={object = DynaText({string = {" "..localize{type = 'variable', key = 'interest', vars = {G.GAME.interest_amount, 5, G.GAME.interest_amount*G.GAME.interest_cap/5}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
                end
'''
match_indent = true
position = "at"
payload = '''
elseif config.name == 'interest' then
	local tbl = G.get_interest_num(false)
	num_dollars = to_number(tbl.money)
	table.insert(left_text, {n=G.UIT.T, config={text = tbl.text, scale = 0.8*scale, colour = tbl.color, shadow = true, juice = true}})
	table.insert(left_text,{n=G.UIT.O, config={object = DynaText({string = {" "..localize{type = 'variable', key = 'interest', vars = {tbl.operator..tbl.intFactor, tbl.intQuantize, tbl.operator..tbl.intFactor*tbl.intCap/5}}}, colours = {G.C.UI.TEXT_LIGHT}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
end
'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
dollars = dollars + G.GAME.interest_amount*math.min(math.floor(G.GAME.dollars/5), G.GAME.interest_cap/5)'''
match_indent = true
position = "at"
payload = '''
dollars = dollars + G.get_interest_num(G.GAME.cry_payload).money
'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
if modded then update_hand_text({sound = 'chips2', modded = modded}, {chips = hand_chips, mult = mult}) end
'''
match_indent = true
position = "after"
payload = '''
G.aejp_tsarlist = {}
for i = 1, #G.jokers.cards do
	G.aejp_tsarlist[i] = false
end
repeat
'''

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''
            SMODS.trigger_effects(effects, _card)
        end end'''
match_indent = true
position = "after" 
payload = '''
			local leave = true
			local table_contains = function(a) 
				for _, q in ipairs(G.aejp_tsarlist or {}) do
					if a == q then
						return true
					end
				return false
				end
			end
			if G.GAME.current_round.hands_left == 0 then
				for k,v in ipairs(G.jokers.cards) do
					if v.ability.name == "j_aejp_bell" and not G.aejp_tsarlist[k] then
						G.aejp_tsarlist[k] = true
						leave = false
						delay(1.25)
						card_eval_status_text(v, "extra", nil, nil, nil, {
							message = localize { type = 'variable', key = 'full_retrigger', vars = { } },
							sound = "talisman_eemult",
							colour = G.ARGS.LOC_COLOURS.weird,
							volume = 0.65
						})
						delay(0.75)
						break
					end
				end
			end
			until leave
'''
# wtf man